### ISSUE TITLE
Curriculum areas should be able to define itself as a subset of another curriculum area

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/cs-unplugged#106]
Also add notice to topics guide that you only need to specify area children (parents are automatically added).

```yaml
  maths:
    name: Maths

  maths-geometry:
    name: Maths - Geometry
    subset_of:
      - maths
```
