### ISSUE TITLE
Update Learning Outcomes config file

### ISSUE THREAD

**Issue by hayleyavw** [uccser/cs-unplugged#261]
Learning Outcomes should be separated into groups, (e.g. computational thinking, curriculum links, etc).

The docs will also need to be updated once this is implemented.

**Comment by JackMorganNZ** [comment]
This should be confirmed with @uccser/cs-unplugged-authors at next meeting.

**Comment by JackMorganNZ** [comment]
Learning outcomes should now also have related curriculum areas, for example:

```
example-key:
    text: "This is the learning outcome text"
    curriculum_areas:
        - writing
        - reading
```
