### ISSUE TITLE
Implement programming exercise language model

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/cs-unplugged#49]
Rather than hard code each programming exercise with Scratch and Python, it should be tied to objects for a particular language, and these can hold the hints and solutions.

**Comment by JackMorganNZ** [comment]
Possible model name `ProgrammingExerciseLanguageSolution`

**Comment by JackMorganNZ** [comment]
Example file: `csunplugged/topics/content/en/binary-numbers/programming-exercises/programming-exercises.yaml`
```yaml
- slug: count-to-10
  exercise-number: 1
  difficulty-level: 1
  md-file: binary-numbers/programming-exercises/exercise-1/index.md
  learning-outcomes:
    - programming-basic-logic
  languages:
    scratch:
      hints: binary-numbers/programming-exercises/exercise-1/scratch-hints.md
      solution: binary-numbers/programming-exercises/exercise-1/scratch-solution.md
    python:
      hints: binary-numbers/programming-exercises/exercise-1/python-hints.md
      solution: binary-numbers/programming-exercises/exercise-1/python-solution.md
```

Example file: `csunplugged/topics/content/en/programming-exercises-difficulty.yaml`
```yaml
languages:
  scratch:
    name: Scratch
    icon: images/scratch-cat.png
  cplusplus:
    name: C++
    icon: images/cpluscplus.png

difficulties:
  - level: 1
    name: Beginner
  - level: 2
    name: Growing Experience
  - level: 3
    name: Ready to Expand
```
